### PR TITLE
Changes 2021 05 20

### PR DESCRIPTION
**Pull request by allemangD**
@bpaniagua These are changes from slicersalt/RigidAlignment that should be pushed upstream to prepare to publish GROUPS to the extension index

### CODE REVIEW

**Review by jcfr — APPROVED** [review]
These changes have been field tested in the version used in SlicerSALT. See https://github.com/slicersalt/RigidAlignment/commits/slicersalt-2021-05-20-7023da49

**Comment by allemangD** [comment]
I've removed https://github.com/slicersalt/RigidAlignment/commit/95b215e476581ba5fb701bfcd4ddfe939c0d1d6a from this PR since it is specific to the SALT modules. Since that change overrides the `suffixe_procalign` and `suffixe_surfSPHARM` parameters and, if it were included here, the suffixes could not be used in any context other than with the SALT names. I'm also going to add a `[slicersalt]` prefix to that commit's message.

Edit: This is done. That change is now at commit https://github.com/slicersalt/RigidAlignment/commit/28be013246f2ca4156a680e5a829c3298e3d2587

**Comment by allemangD** [comment]
I'm getting a bit confused here... We need to have that change here, since we want this module to work with SPHARM-PDM on the extension manager, but I don't want to just override the parameters.

I see there are default values set in `RigidAlignment.xml`. I've added the missing underscore to those, and removed the code which overrides the parameter. https://github.com/NIRALUser/RigidAlignment/pull/5/commits/27d13fc36f54511aba18c02c1195f3612e934b52

This way the parameter should still work correctly, but the default values should be the one output by SPHARM-PDM.

I've also done this in https://github.com/slicersalt/RigidAlignment/commits/slicersalt-2021-05-20-7023da49

**Comment by jcfr** [comment]
> Edit: This is done. That change is now at commit slicersalt@28be013

Clicking on the link indicates `This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.`, let's make sure it associated with a branch in the fork.

**Comment by allemangD** [comment]
After I realized that the fix does need to be present I removed that commit and replaced it with the change I mention in this comment https://github.com/NIRALUser/RigidAlignment/pull/5#issuecomment-845234492

**Comment by jcfr** [comment]
> but the default values should be the one output by SPHARM-PDM.

Do you have reference to the `SPHARM-PDM` code ?

**Comment by allemangD** [comment]
https://github.com/NIRALUser/SPHARM-PDM/blob/master/Modules/Scripted/ShapeAnalysisModule/ShapeAnalysisModule.py#L1914-L1917

https://github.com/NIRALUser/SPHARM-PDM/blob/master/Modules/Scripted/ShapeAnalysisModule/ShapeAnalysisModule.py#L1308

**Review by jcfr — APPROVED** [review]

**Pull request merged**
